version: '3.1'

services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sejongroot
      MYSQL_DATABASE: sejong
      MYSQL_USER: sejong
      MYSQL_PASSWORD: sejongpassword
    volumes:
      - ./local-db:/var/lib/mysql
